<?php

namespace Test\TripServiceKata\Trip;

use PHPUnit\Framework\TestCase;
use TripServiceKata\Exception\UserNotLoggedInException;
use TripServiceKata\Trip\TripService;
use TripServiceKata\User\User;

class TestableTripService extends TripService
{
    protected function getLoggedUser(): ?User
    {
        return null; // TODO: Change the autogenerated stub
    }
}

class TripServiceShould extends TestCase
{
    private $tripService;
    const FRIEND_NAME = "A friend";

    /**
     * @test
     */
    public function throw_exception_if_user_is_not_logged_in(): void
    {
        $this->expectException(UserNotLoggedInException::class);
        $tripService = new TestableTripService();
        $tripService->getTripsByUser(new User(self::FRIEND_NAME));
    }
}
